say:
  name: ZALO.AI TTS
  description: Chuyển văn bản thành giọng nói tiếng Việt và phát lên thiết bị media_player.
  fields:
    entity_id:
      name: Thiết bị phát
      description: ID của media_player để phát giọng nói.
      required: true
      advanced: true
      example: media_player.home
      selector:
        entity:
          domain: media_player

    message:
      name: Nội dung
      description: Văn bản tiếng Việt muốn chuyển thành giọng nói.
      required: true
      advanced: true
      example: "Đây là nội dung mẫu"
      default: ""
      selector:
        text:
          multiline: true

    speed:
      name: Tốc độ đọc
      description: Tốc độ nói từ 0.8 (chậm) đến 1.2 (nhanh). Mặc định lấy từ configuration.yaml nếu không điền.
      required: true
      advanced: true
      example: "0.8"
      default: "0.8"
      selector:
        number:
          min: 0.8
          max: 1.2
          step: 0.1
          mode: slider

    voice:
      name: Kiểu giọng
      description: Chọn giọng đọc phù hợp (giới tính và vùng miền).
      required: true
      advanced: true
      example: "1"
      default: "1"
      selector:
        select:
          options:
            - label: "Nữ miền Nam 1"
              value: "1"
            - label: "Nữ miền Bắc 1"
              value: "2"
            - label: "Nam miền Nam"
              value: "3"
            - label: "Nam miền Bắc"
              value: "4"
            - label: "Nữ miền Bắc 2"
              value: "5"
            - label: "Nữ miền Nam 2"
              value: "6"
